import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  // But you can create a sidebar manually

  notesSidebar: [
    {
      type: 'category',
      label: 'Fastify',
      items: ['fastify/setup', 'fastify/routes', 'fastify/validation', 'fastify/database'],
    },
    {
      type: 'category',
      label: 'Tmux',
      items: ['tmux/commands'],
    },
    {
      type: 'category',
      label: 'Vim',
      items: ['vim/keybindings'],
    },
    {
      type: 'category',
      label: 'Lua',
      items: ['lua/basics', 'lua/control-flow'],
    },
    {
      type: 'category',
      label: 'Linux',
      items: ['linux/commands'],
    },
  ],
};

export default sidebars;
